name: Build frontend
on: [push, workflow_dispatch]
jobs:
    Fetch code:
        runs-on: ubuntu-latest
        steps:
            - name: clone repo
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    Compile Code:
        needs: Fetch code
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Compile code
              run: npm run build

          
